_SORT_SUFFIX = '?sort={}'
_YESTERDAY_SUFFIX = '?yesterday=true'
_YESTERDAY_SORTED = '?yesterday=true&sort={}'

GLOBAL_DATA = '{}/v2/all'
GLOBAL_YESTERDAY = GLOBAL_DATA + _YESTERDAY_SUFFIX

ALL_COUNTRIES = '{}/v2/countries'
ALL_COUNTRIES_SORTED = ALL_COUNTRIES + _SORT_SUFFIX
ALL_COUNTRIES_YESTERDAY = ALL_COUNTRIES + _YESTERDAY_SUFFIX
ALL_COUNTRIES_YESTERDAY_SORTED = ALL_COUNTRIES + _YESTERDAY_SORTED

COUNTRY_DATA = '{}/v2/countries/{}'
COUNTRY_DATA_YESTERDAY = COUNTRY_DATA + _YESTERDAY_SUFFIX

ALL_STATES = '{}/v2/states'
ALL_STATES_SORTED = ALL_STATES + _SORT_SUFFIX
ALL_STATES_YESTERDAY = ALL_STATES + _YESTERDAY_SUFFIX
ALL_STATES_YESTERDAY_SORTED = ALL_STATES + _YESTERDAY_SORTED

SINGLE_STATE = '{}/v2/states/{}'
SINGLE_STATE_YESTERDAY = SINGLE_STATE + _YESTERDAY_SUFFIX

HISTORICAL_COUNTRY = '{}/v2/historical/{}?lastdays={}'
HISTORICAL_PROVINCE = '{}/v2/historical/{}/{}?lastdays={}'
STATE_COUNTY = '{}/v2/historical/usacounties/{}?lastdays={}'

ALL_CONTINENTS = '{}/v2/continents'
ALL_CONTINENTS_SORTED = ALL_CONTINENTS + _SORT_SUFFIX
ALL_CONTINENTS_YESTERDAY = ALL_CONTINENTS + _YESTERDAY_SUFFIX
ALL_CONTINENTS_YESTERDAY_SORTED = ALL_CONTINENTS + _YESTERDAY_SORTED

CONTINENT_DATA = '{}/v2/continents/{}'
CONTINENT_YESTERDAY = CONTINENT_DATA + _YESTERDAY_SUFFIX

JHU_CSSE = '{}/v2/jhucsse'
JHU_CSSE_COUNTIES = '{}/v2/jhucsse/counties/{}'